# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df36af5bead81bcf834ac7776a33c9ed64bc840556878062a9a8f38a8642872cd602b6c925f543816b624bc37bb5fe9a2306851903143b638dcdedbc29f66007

test:
  secret_key_base: 4d2c4a15e687ae5c65c3c91d38415d47bc53e474dee10ea50d1593f0688d970c07b8c3868ca6ad02b42da16b14fcefad5b33ef626e44ae0bf1a8c93dfed8892a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
